# Generated by Django 3.0.5 on 2020-06-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimes',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
